version = "1.1.0"

[class]
mpv = ""
foot = " "
anki = "日本語"
steam = "󰓓 "
parsecd = "󱌣 "
"[Ff]irefox" = " "
DEFAULT = " {class} "
libreoffice-writer = "󱎒 "
libreoffice-calc = "󱎏 "
osu = "<span color='#F28FAD'>󰎈</span>"
nheko = "<span color='#ABE9B3'>󰊌</span>"

[class_active]

[initial_class]

[initial_class_active]

[title_in_class]

[title_in_class_active]

[title_in_initial_class]

[title_in_initial_class_active]

[initial_title_in_class]

[initial_title_in_class_active]

[initial_title_in_initial_class]

[initial_title_in_initial_class_active]

[exclude]

[format]
dedup = true
dedup_inactive_fullscreen = false
delim = " "
workspace = "{id}:{delim}{clients}"
workspace_empty = "{id}"
client = "{icon}"
client_fullscreen = "{icon}^"
client_active = "<span color='#F8BD96'>[</span>{icon}<span color='#F8BD96'>]</span>"
client_dup = "{icon}  {counter_sup}{delim}"
client_dup_active = "*{icon}*{delim}{icon}{counter_unfocused_sup}"
client_dup_fullscreen = "[{icon}]{delim}{icon}{counter_unfocused_sup}"
