
# Deduplicate icons if enable.
# A superscripted counter will be added.
dedup = false

[icons]
# Add your icons mapping
# use double quote the key and the value
# take class name from 'hyprctl clients'
"foot" = ""
"DEFAULT" = " ${class} "
"[Ff]irefox" = ""
"mpv" = ""
"osu" = "󰎈"

[title."firefox"]
".*Discord.*" = "󰙯"
".*GitHub.*" = ""

[exclude]
