
# Deduplicate icons if enable.
# A superscripted counter will be added.
dedup = false

[icons]
# Add your icons mapping
# use double quote the key and the value
# take class name from 'hyprctl clients'
"foot" = ""
"DEFAULT" = " ${class} "
"[Ff]irefox" = ""
"mpv" = ""
"osu" = "󰎈"

[title."(?i)kitty"]
"(?i)neomutt" = "neomutt"

[title."firefox"]
".*Discord.*" = "󰙯"
".*GitHub.*" = ""

# Add your applications that need to be exclude
# The key is the class, the value is the title.
# You can put an empty title to exclude based on
# class name only, "" make the job.
[exclude]
"(?i)fcitx" = ".*" # will match all title for fcitx
"(?i)TestApp" = "" # will match all title for TestApp
aProgram = "^$" # will match null title for aProgram
"[Ss]team" = "Friends List.*"
"[Ss]team" = "^$" # will match all Steam window with null title (some popup)
