# Deduplicate icons if enable.
# A superscripted counter will be added.

[format]
dedup = true
client_fullscreen = "「{icon}」"
client_dup = "{icon}  {counter_sup}{delim}"

[icons]
# Add your icons mapping
# use double quote the key and the value
# take class name from 'hyprctl clients'
"foot" = ""
"DEFAULT" = " ${class} "
"[Ff]irefox" = ""
"mpv" = ""
"osu" = "󰎈"
"libreoffice-writer" = "󱎒"
"libreoffice-calc" = "󱎏"

"parsecd" = "󱌣"

[title."firefox"]
".*Discord.*" = "<span color='#768ED3'>󰙯</span>"
".*GitHub.*" = "󰊤"

[title."foot"]
".*ytfzf$" = "<span color='#F28FAD'></span>"
"^nvim" = '<span color="#7CB764"></span>'
