background: "#21143e"
border: "#89dceb"
color: "#cba6f7"

inhibit_compositor_keyboard_shortcuts: true
auto_kbd_layout: true

menu:
  - key: "g"
    desc: "application launch"
    submenu:
      - key: "Mod4+O"
        desc: "osu lazer"
        cmd: "osu-lazer"
      - key: "Mod4+o"
        desc: "osu"
        cmd: "systemctl --user enable --now opentabletdriver; osu-stable"
      - key: "Mod4+y"
        desc: "search and copy youtube url"
        cmd: "ytfzf -cyt -LD | wl-copy"
      - key: "Mod4+q"
        desc: "quickmedia"
        cmd: "quickmedia"
      - key: "Mod4+M"
        desc: "open copied url in mpv"
        cmd: 'mpv --no-terminal "$(wl-paste -p)" || mpv --no-terminal "$(wl-paste)"'
      - key: "Mod4+comma"
        desc: "connect to wifi"
        cmd: "wifi-con"
      - key: "Mod4+g"
        desc: "color picker"
        cmd: "$TERMINAL -a goker goker"
      - key: "Mod4+V"
        desc: "audio mixer"
        cmd: "$TERMINAL -t foot-direct -e pulsemixer"
      - key: "Mod4+v"
        desc: "set sink"
        cmd: "set-sink"
      - key: "Mod4+j"
        desc: "japanese dictionary"
        cmd: "tagainijisho"
      - key: "Mod4+s"
        desc: "AIOOOOO desktop"
        cmd: "gtk-launch AIO.desktop"
      - key: "s"
        desc: "AIOOOOO search"
        cmd: '_BROWSER_NO_PRIVACY "https://$(cat $HOME/Documents/APIKeys/AIO | base64 -d -w0)@cloud:8887/login?uid=1&q=$(rofi -dmenu -p "aio serach" -theme  cat-macchiato-dmenu-center)"'

  - key: "b"
    desc: "bookmarks"
    submenu:
      - key: "Mod4+d"
        desc: "discord"
        cmd: "$BROWSER_LITE https://discord.com/login"
      - key: "Mod4+p"
        desc: "open pacman package url"
        cmd: 'proj="$(pacman-url-picker)"; [ "$proj" ] && $BROWSER "$proj"'
      - key: "Mod4+P"
        desc: "copy pacman project url"
        cmd: 'proj="$(pacman-url-picker)"; [ "$proj" ] && printf "%s" "$proj" | wl-copy'
      - key: "Mod4+b"
        desc: "open bookmark"
        cmd: "linkding-cli open"
      - key: "d"
        desc: "delete bookmark"
        cmd: "linkding-cli remove"
      - key: "Mod4+c"
        desc: "copy bookmark"
        cmd: "linkding-cli copy"
      - key: "Mod4+t"
        desc: "copy bookmark tag"
        cmd: "linkding-cli list-tags | rofi -dmenu -theme cat-macchiato -i -p \"Select tag\" | wl-copy -n"
      - key: "Mod4+a"
        desc: "add bookmark"
        cmd: "linkding-cli add"
