#!/bin/bash

export WM="${WM:-sway}"

export GDK_BACKEND=wayland,x11
export QT_QPA_PLATFORM="wayland;xcb"
export SDL_VIDEODRIVER=wayland
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1

# mako & disown
moxnotify & disown
brightnessctl s 100%

# case "$XDG_CURRENT_DESKTOP" in
#     Hyprland)
#         hyprland keyword monitor HDMI-A-1,1920x1080@75,1920x0,1
#         hyprland keyword monitor DP-1,1920x1080@165,0x0,1
#         hyprland keyword monitor DP-3,disable ;;
#     *)
#         wlr-randr --output DP-3 --off
#         wlr-randr --output HDMI-A-1 --pos 1920,0
#         wlr-randr --output DP-1 --pos 0,0 ;;
# esac
#

restart-waybar
restart-wallpaper

# wallpaper-slideshow $((60 * 10)) & disown

# killall swayidle
# swayidle timeout $((60 * 20)) $LOCKER & disown

dbus-update-activation-environment --systemd --all

killall fcitx5
fcitx5 -d & disown

#needs manual intervention
/usr/lib/xdg-desktop-portal-termfilechooser -r & disown

# killall workspace-iconifier
# workspace-iconifier & disown

# killall hyprland-activity-tracker
# hyprland-activity-tracker & disown

killall jellyfin-mpv-shim
jellyfin-mpv-shim & disown

# kilall dvd-auto-play
# dvd-auto-play & disown

export XDG_CURRENT_DESKTOP=Hyprland

eval $CALENDAR &
$GUIEDITOR $WIKI/TODO.mmfml &
