#!/bin/bash

tmp="$(mktemp)"

#let user choose location/file
xdg-desktop-portal.FileChooser 0 0 1 "$CLOUD/Pictures" "$tmp"

path="$(cat "$tmp")"
[ -z "$path" ] && exit

case "$(printf "%s\n" "use clipboard" "take screenshot" | rofi -dmenu -theme cat-macchiato)" in
    "use clipboard")
        wl-paste -t image/png > "$path"
        ;;
    "take screenshot")
        scr-wayland "" libjxl && wl-paste -t image/png > "$path"
        ;;
esac
