#!/bin/bash

mksearch() {
    local search=$1
    curl "$AIO_SERVER/api/v1/query-v3" -G --data-urlencode "search=@${search}" | jq -r '"\(.ItemId)\t\(.En_Title)\t\(.Type)\t\(.Location)"'
}

mkselection() {
    local results="$1"
    echo "$results" | fzf -1
}

evallocation() {
    local location="$1"
    eval printf "%s" "\"$location\""
}

getpos() {
    local id=$1
    local pos=$(curl "$AIO_SERVER"/api/v1/engagement/get-entry -G --data-urlencode "uid=${AIO_UID}" --data-urlencode "id=${id}" | jq -r '.CurrentPosition')
    pos="$(printf "%s" "$pos" | sed -n 's/.*\([[:digit:]]\+\).*/\1/p')"
    printf "%d" "$((pos + 1))"
}

getsubs() {
    local pos="$1"
    local location="$2"
    printf "%s\n" "Finding subfiles for episode: $pos"
    valid=""
    while read -r file; do
        [ -z "$file" ] && continue
        if [ "$(episode-grabber.py "$file" "${file%/*}")" -eq "$pos" ]; then
            valid=$(printf "%s\n%s" "$valid" "$file")
        fi
    done <<<"$(fd -i sub "$location" | xargs -I{} fd . "{}")"

    [ "$valid" ] && printf "%s" "${valid#$'\n'}" | fzf -1
}

getseason() {
    local location="$1"
    seasons=""
    for file in "$location"/[Ss]eason*; do
        case "$file" in
        *'[Ss]eason*') continue ;;
        esac
        seasons="$(printf '%s\n%s' "$seasons" "${file##*/}")"
    done
    for file in "$location"/[Ss][[:digit:]]*; do
        case "$file" in
        *'[Ss][[:digit:]]*') continue ;;
        esac
        seasons="$(printf '%s\n%s' "$seasons" "${file##*/}")"
    done
    [ "$seasons" ] && printf "%s" "${seasons#$'\n'}" | fzf -1
}

findfile() {
    local location="$1"
    while read -r file; do
        if [ "$(episode-grabber.py "$file" "$location" i)" = "$pos" ]; then
            printf "%s" "$file"
            break
        fi
    done <<<"$(ls "$location")"
}

play() {
    local subs=$1
    local path=$2

    if [ "$subs" ]; then
        mpv --sub-file="${subs}" "$path"
    else
        mpv "$path"
    fi
}

ask_subs=0
while getopts "s" OPT; do
    case "$OPT" in
    s) ask_subs=1 ;;
    *) : ;;
    esac
done
shift $((OPTIND - 1))

search=$*
search="${search// /\\ }"
main() {
    results="$(mksearch "$search")"

    selection="$(mkselection "$results")"
    IFS=$'\t' read -r id name type location <<<"$selection"

    location="$(evallocation "$location")"

    pos=$(getpos "$id")

    [ "$ask_subs" = 1 ] && subsloc=$(getsubs "$pos" "$location")

    season="$(getseason "$location")"
    [ "$season" ] && location="${location}/${season}"

    case "$type" in
        Show) location="${location}/$(findfile "$location")" ;;
    esac

    play "$subsloc" "$location"
}

main
