#!/bin/bash

displayThumbId=$1
tmpMetadata="${2:-$(mktemp)}"

aioUrl="http://localhost:8080/api/v1"

[ -s "$tmpMetadata" ] && metadata="$(cat "${tmpMetadata}")" || metadata=$(curl "${aioUrl}/metadata/list-entries" 2>/dev/null | tee "$tmpMetadata")

if [ "$displayThumbId" ]; then
    thumb=$(jq -rs ".[]|select(.ItemId==${displayThumbId}).Thumbnail" <<< "$metadata")
    jq -rs ".[]|select(.ItemId==${displayThumbId}).Title" <<< "$metadata"
    if ! [ "$thumb" ]; then
        echo "NO THUMBNAIL"
    else
        printf "%s" "$thumb" | xargs -I{} curl "${aioUrl%/api/v1}{}" 2>/dev/null | chafa
    fi
    exit 0
fi

read -r -p "Account pin (press enter to skip): " pin

auth=$(printf ":%s" "$pin" | base64)

data=$(curl "${aioUrl}/query-v3" -G -d 'search=location!=""')

ids=$(printf "%s" "$data" | jq -s '.[]|.ItemId')

display=$(printf "%s" "$data" | jq -rs $'.[]|"\(.En_Title) : \(.ItemId)"')

getThumbPath() {
    id=$1

    jq -rs ".[]|select(.ItemId==${id}).Thumbnail" <<<"$metadata"
}

id=$(printf "%s" "$display" | fzf --preview 'echo {} | rev | cut -d: -f 1 | rev | xargs -I.PL. '"$0"' .PL. '"${tmpMetadata}"' ' | rev | cut -d: -f 1 | rev)

linkhandler media://"$(printf "%s" "$data" | jq -rs ".[]|select(.ItemId==${id}).Location")"

rm "$tmpMetadata"
