#!/bin/bash

displayThumbId=$1
tmpMetadata="${2:-$(mktemp)}"

aioUrl=${AIO_SERVER:-"http://localhost:8080"}"/api/v1"

[ -s "$tmpMetadata" ] && metadata="$(cat "${tmpMetadata}")" || metadata=$(curl "${aioUrl}/metadata/list-entries" 2>/dev/null | tee "$tmpMetadata")

tmp="/tmp/aiow-${displayThumbId}.txt"
if [ "$displayThumbId" ]; then
    if [ -s "$tmp" ];then
        cat "$tmp"
    else
        thumb=$(jq -rs ".[]|select(.ItemId==${displayThumbId}).Thumbnail" <<<"$metadata")
        desc=$(jq -rs ".[]|select(.ItemId==${displayThumbId})|.Title + \" (\(.Rating))\" + \"<br><br>\" + .Description" <<<"$metadata" | pandoc -fhtml -tgfm)
        printf "%s" "$desc" | tee -a "$tmp"
        if ! [ "$thumb" ]; then
            echo "NO THUMBNAIL"
        else
            desc_height=$(($(printf "%s" "$desc" | wc -l)))
            printf "%s" "$thumb" | xargs -I{} curl "${aioUrl%/api/v1}{}" 2>/dev/null | chafa -s "$((FZF_PREVIEW_COLUMNS))x$((FZF_PREVIEW_LINES - desc_height))" | tee -a "$tmp"
        fi
    fi
    exit 0
fi

#format 9 is special, because only the game id need be stored, in MediaDependant for it to be able to open it
data=$(curl "${aioUrl}/query-v3" -G -d 'search=location!=""|format==9')

ids=$(printf "%s" "$data" | jq -s '.[]|.ItemId')

display=$(printf "%s" "$data" | jq -rs $'.[]|"\(.En_Title) : \(.ItemId)"')

getThumbPath() {
    id=$1

    jq -rs ".[]|select(.ItemId==${id}).Thumbnail" <<<"$metadata"
}

id=$(printf "%s" "$display" | fzf --preview 'echo {} | rev | cut -d: -f 1 | rev | xargs -I.PL. '"$0"' .PL. '"${tmpMetadata}"' ' | rev | cut -d: -f 1 | rev)

type="$(printf "%s" "$data" | jq -rs ".[]|select(.ItemId==${id}).Type")"
format="$(printf "%s" "$data" | jq -rs ".[]|select(.ItemId==${id}).Format")"

mdmeta=$(printf "%s" "$metadata" | jq -rs ".[]|select(.ItemId==${id}).MediaDependant")

prefix="media://"
case "$type" in
Game) prefix="exe://" ;;
esac
[ "$format" = 9 ] && {
    gameId=$(printf "%s" "$mdmeta" | jq -r '.["Game-steam-id"]')
    [ "$gameId" != "null" ] && {
        prefix="steam://rungameid/${gameId}"
    }
}

linkhandler "${prefix}""$(printf "%s" "$data" | jq -rs ".[]|select(.ItemId==${id}).Location")"

rm "$tmpMetadata"
