#!/bin/bash

# this script recursively converts all non-mp3 audio/video files in a folder to mp3 files
# the new mp3 file is saved as ${originalname}.mp3, the previous file sufix does not get removed

convert () {
    ffmpeg -loglevel error -i "$1" "$1.mp3"
    rm "$1"
    printf "%s\n" "Completed: $1"
}


fd | grep -v 'mp3$' | while read -r song; do
    convert "$song" &
done
