#!/bin/bash

action=$1

bookmark_dir="${XDG_DOCUMENTS_HOME}/bookmarks"

open() {
	file=$(find "$bookmark_dir/" -type f -printf "%P\n" | while read -r line; do
		printf "%s\n" "$line"
	done | column -s$'\t' -t -c 1000 | rofi -p "open" -i -dmenu -theme cat-macchiato)

	[ -z "$file" ] && exit

	file="${file%%  *}"

	path="${bookmark_dir}/${file}"
	text=$(cat "$path")
	requested_exec="$(grep '^exec=' <<<"$text" | cut -d '=' -f2-)"
	url="$(grep "^url=" <<<"$text" | cut -d '=' -f2-)"
    linkhandler "${url}"
}

add() {
	folder=$(find "$bookmark_dir/" -type d -printf '%P/\n' | rofi -p 'folder' -i -dmenu -theme cat-macchiato)
	[ -z "$folder" ] && exit
	mkdir -p "${bookmark_dir}/$folder"
	IFS="|" read name url keyword <<<"$(zenity --forms --add-entry='name' --add-entry='url' --add-entry='keyword')"
	[ -z "$url" ] && { zenity --question --text="<b>$(wl-paste)</b>\nwill be used as the url since you did not provide one" && url="$(wl-paste)" || exit 1; }
	printf "url=%s\nkeyword=%s" "$url" "$keyword" >"${bookmark_dir}/${folder}/${name}"
}

remove() {
	file=$(find "$bookmark_dir/" -type f -printf "%P\n" | rofi -p "remove" -i -dmenu -theme cat-macchiato)
	[ -z "$file" ] && exit
	path="${bookmark_dir}/${file}"

	zenity --question --text="Are you sure you want to remove\n<b>${file}</b>" || exit 1

	rm "${path}"
}

copy() {
	file=$(find "$bookmark_dir/" -type f -printf "%P\n" | while read -r line; do
		printf "%s\n" "$line"
	done | column -s$'\t' -t -c 1000 | rofi -p "copy" -i -dmenu -theme cat-macchiato)

	[ -z "$file" ] && exit

	file="${file%%  *}"

	path="${bookmark_dir}/${file}"
	grep "^url=" "$path" | cut -d '=' -f2- | tr -d $'\n' | wl-copy
}

search() {
	q="$*"
	kwd_bookmarks=$(rg 'keyword=(.+)' $bookmark_dir | sed "s_${bookmark_dir}/__" | awk -F':keyword=' '{print $2, $1}')
	[ -z "$q" ] && q="$(echo "$kwd_bookmarks" | rofi -format f -dmenu -p "Query: " -theme cat-macchiato)"

	[ -z "$q" ] && return 1

	words=($q)

	keyword="${words[0]}"

	path=$(rg -l "keyword=${keyword}\$" "$bookmark_dir" | head -n1)

	if [ "$path" ]; then
		url="$(grep "^url=" "$path" | cut -d '=' -f2-)"
		linkhandler "$(printf "$url" "${words[*]:1}")"
	else
		$BROWSER --search "$q"
	fi
}

case "$action" in
open | o) open ;;
add | a) add ;;
remove | r) remove ;;
copy | c) copy ;;
search | s)
	shift
	search "$@"
	;;
*) printf "%s\n" "$action is not a valid action" ;;
esac
