#!/bin/bash

path=$1
path="${path##*$'\t'}"
path="$(eval echo '"'"$path"'"')"

while [ -d "$path" ]; do
    if [ -d "$path" ]; then
        [ -n "$(find "$path" -maxdepth 1 -iname "*.nfo")" ] &&
            find "$path" -maxdepth 1  -iname '*.nfo' -exec cat '{}' ';' &&
            break
    elif [ -f "$path" ]; then
        [ -n "$(find "${path%/*}" -maxdepth 1 -iname "*.nfo")" ] &&
            find "${path%/*}" -maxdepth 1  -iname '*.nfo' -exec cat '{}' ';' &&
            break
    fi
    path="${path%/*}"
done
