#!/bin/bash

path=$1
path="${path##*$'\t'}"
path="$(eval echo '"'"$path"'"')"

if [ -d "$path" ]; then
    find "$path" -iname '*.nfo' -exec cat '{}' ';'
elif [ -f "$path" ]; then
    find "${path%/*}" -iname '*.nfo' -exec cat '{}' ';'
else
    exit 1
fi
