#!/bin/sh

input="$1"
output_dir="$2"

[ -z "$input" ] && {
    printf "%s\n" "Must provide input file"
    exit 1
}

[ -z "$output_dir" ] || ! [ -d "$output_dir" ] || [ "$(ls -1 "$output_dir" | wc -l)" -gt 0 ] && {
    printf "%s\n" "Must provide an empty output directory"
    exit 1
}

ffprobe -i "$input" -show_chapters -of json |
    jq -r '.chapters|.[]|"\(.start_time) \((.end_time|tonumber) - (.start_time|tonumber))"' |
    while read -r start duration; do
        echo "$start" "${duration%.*}"
        count=$(ls -1 "$output_dir" | wc -l)
        ffmpeg -ss "$start" -i "$input" -map 0 -c copy -t "${duration%.*}" "$output_dir"/$((count+1)).mkv
    done
