#!/bin/bash

[ -n "$*" ] && { 
    e="${*#*://}"
}

[ -z "$*" ] && {
    e="$(printf "" | rofi -dmenu -p "Calc: " -theme cat-macchiato-dmenu-center -theme-str '#element-text selected { background-color: transparent; }')" 
}

[ -z "$e" ] && exit

ans="$(qalc -t "${e}")"

case "$XDG_SESSION_TYPE" in
    wayland) wl-copy  -- "$ans" ;;
    X11) xclip -i <<< "$ans" ;;
esac

notify-send -- "$ans"
