#!/bin/bash

pos=$(hyprctl clients -j |
    jq -r '.[]|"\(.at[0]),\(.at[1]) \(.size[0])x\(.size[1])"' |
    slurp -r)
grim -t png -g "$pos" /dev/stdout | wl-copy
t=$(mktemp)
wl-paste > $t
notify-send -c screenshot -i $t "Image taken at: $pos"
rm $t
