#!/bin/bash

section='languages'
exclude_unknown=0

range=""

while getopts pUr: OPT; do
    case $OPT in
    p) section='projects' ;;
    U) exclude_unknown=1 ;;
    r) range=$OPTARG ;;
    *) : ;;
    esac
done

shift $((OPTIND - 1))

convertsecs() {
    ((h = ${1} / 3600))
    ((m = (${1} % 3600) / 60))
    ((s = ${1} % 60))
    printf "%02d:%02d:%02d\n" $h $m $s
}

milestones=(50)
if [ -n "$*" ]; then
    milestones=($(echo "$*" | tr '[:space:]' $'\n' | sort -n))
fi

total_pct=0
total_secs=0
cur_milestone=0
lang_count=0
{
    while read -r lang secs pct; do
        [ "$exclude_unknown" = 1 ] && [ "${lang,,}" = "unknown" ] && continue

        total_pct=$(echo "$total_pct + ${pct}" | bc)
        total_secs=$((total_secs + secs))

        lang_count=$((lang_count + 1))

        echo "$lang $(convertsecs "$secs") ($pct)"

        milestone_nr=${milestones[$cur_milestone]}
        while [ -n "$milestone_nr" ] && [ "$(bc <<<"${total_pct} > ${milestone_nr}")" = 1 ]; do
            printf "\x1b[1m%s%%-(%d) %s (%.2f%%)\x1b[0m\n" "$milestone_nr" "$lang_count" "$(convertsecs "$total_secs")" "${total_pct}"
            cur_milestone=$((cur_milestone + 1))
            milestone_nr=${milestones[$cur_milestone]}
        done
    done <<<"$(
        curl -s http://cloud:54321/api/compat/wakatime/v1/users/euro/stats/"$range" |
            jq -r .data."$section"'.[]|"\(.name)\t\(.total_seconds)\t\(.percent)"'
        )"

    printf -- "-------------\nTOTAL %s (100%%)\n" "$(convertsecs "$total_secs")"
} | column -t
