#!/bin/sh

link="$*"

mime=$(file --mime-type "$*" | cut -d: -f2 | tr -d ' ')

website="$(printf "%s" "$link" | grep -Po "://.*?/" | sed -E 's/(:\/)?\///g')"

case "$mime" in
    image/*) sxiv "$link"; exit 0;;
esac
case "$link" in
    file://*) $TERMINAL $EDITOR "$link" ;;
    *.png|*.jpg|*.jpeg|*.webm|*.gif|*.webm|*.webp) mpv --loop "$link" & ;;
    term://*) "${TERMINAL}" "${TERMINAL_HOLD_OPT:="-H"}" -e "${link#term://}";;
    *)
        if yt-dlp -s "$link" > /dev/null 2>&1; then
            nohup mpv --geometry=1000 --loop "$link" > /dev/null 2>&1 &
        else
            nohup $BROWSER_LITE "$link" > /dev/null 2>&1 &
        fi;;
esac
