#!/bin/bash
#LH_NO_EDIT is used in my nvim config to say, dont edit just exit with an error to let nvim handle the editing

link="$*"
: "${LH_NO_EDIT=0}"
: "${LINKHANDLER_EXPAND_ONLY:-0}"

# EDITOR="$TERMINAL $EDITOR"
#

open_with_editor() {
    modified_link="$1"

    #If nvim is open and linkhandler was opened from nvim, open in a new tab in the current instance of nvim
    [ "$NVIM" ] && nvim --headless --server "$NVIM" --remote-send ":tabnew $modified_link<CR>" || {
        if tty 2> /dev/null 1>&2; then
            "$EDITOR" "$modified_link"
        else
            ${GUIEDITOR} "$modified_link"
        fi
    }
    return 0
}

try_mime_handling() {
    #rev cut rev gets the last field
    mime=$(file --mime-type "$link" | rev | cut -d: -f1 | rev | tr -d ' ')
    case "$mime" in
        application/pdf | application/epub*) zathura "$link" ;;
        image/*) sxiv "$link" ;;
        text/html) $BROWSER "$link" ;;
        text/* | plain/*)
            [ $LH_NO_EDIT = 1 ] && exit 1
            open_with_editor "$link" ;;
        video/* | audio/*) mpv "$link" ;;
        application/x-shockwave-flash) flashplayer "$link" ;;
        inode/directory) open_with_editor "$link" ;;
        *) return 1 ;;
    esac
    return 0
}

try_custom_uri() {
    case "$link" in
        *.swf) flashplayer "$link" ;;
        *.png | *.jpg | *.jpeg | *.webm | *.gif | *.webm | *.webp) mpv --loop "$link" & ;;
        *.m3u?) mpv "$link" ;;
        *.onion) tor "$link" ;;
        *://cloud://*)
            extra_protocol="${link%%cloud://*}"
            new_link="${extra_protocol}${CLOUD}/${link#*://cloud://}"
            linkhandler "$new_link"
            exit
            ;;
        # steam://*) flatpak run com.valvesoftware.Steam "$link" ;;
        jellyfin://*)
            show="${link#jellyfin://}"
            IFS=: read -r show season episode <<< "$show"
            show="$(printf "%s" "$show" | jq -sRr @uri)"
            echo "$show"
            aiow -d '\(if .Type != "Series" then "\(.SeriesName) " else "" end)[\(.Type)\(if .Type == "Episode" then
                    " : \(.IndexNumber), S\(.ParentIndexNumber)"
                elif .Type == "Season" then
                    " : S\(.IndexNumber)"
                else
                    ""
                end)] \(.Name)' "$show" 'IncludeItemTypes=Series,Movie,Episode'
            ;;
        exe://*) "${link#exe://}" ;;
        media://*) mpv "${link#media://}" ;;
        https://cdn.discordapp.com/attachments/*)
            tmp=$(mktemp)
            curl "$link" >"$tmp"
            linkhandler "$tmp"
            rm "$tmp"
            ;;
        https://github.com/*/blob/*)
            [ "$LH_NO_EDIT" = 1 ] && exit 1
            file_path=${link#*/blob/}
            repo="${link%%/blob/*}"
            repo="${repo#https://github.com/}"
            open_with_editor "https://raw.githubusercontent.com/${repo}/${file_path}"
            ;;
        https://*/watch?v=* | https://youtu.be*) mpv "$link" ;;
        https://* | http://* | file:///*) nohup "$BROWSER" "$link" >/dev/null 2>&1 & ;;
        gemini://*) ${GEMINI:-kristall} "$link" ;;
        term://*) "${TERMINAL}" "${TERMINAL_HOLD_OPT:="-H"}" -e "${link#term://}" ;;
        man://* | man:)
            grep -q '.*nvim.*' <<EOF || [ "$NVIM" ] && { link="${link#man://}"; }
$MANPAGER
EOF
            #If nvim is open and man:// was opened from nvim, open in a new tab in the current instance of nvim
            [ "$NVIM" ] && nvim --headless --server "$NVIM" --remote-send ":tab Man $link<CR>" || "${TERMINAL}" man "$link"
            ;;
        sftp://*) mpv "$link" ;;
        /* | ~/* | ./*)
            [ "$LH_NO_EDIT" = 1 ] && exit 1
            open_with_editor "$link"
            ;;
        *) xdg-open "$link" 2>/dev/null || "$BROWSER" "$link" ;;
    esac
}

#modifies $link
expand_path_uri() {
    case "$link" in
        cloud:*//*)
            extra="${link#cloud:}"
            extra="${extra%%//*}"
            case "$extra" in
                /*) path="${extra#/}://$CLOUD/${link#cloud:*//}" ;;
                :*) path="${extra#:}:$CLOUD/${link#cloud:*//}" ;;
                *) path="$CLOUD/${link#cloud:*//}" ;;
            esac
            link="$path" ;;
        vimwiki:*) link="$WIKI/${link#vimwiki:}" ;;
        wiki://*) link="https://wikipedia.org/wiki/${link#wiki://}" ;;

        anime:sftp://*) link="${link#anime:}" ;;&
        sftp://*)
            eval "$(ssh-agent -s)"
            SSH_ASKPASS="$HOME/.local/scripts/ssh-askpass" ssh-add ~/.ssh/id_cloud ;;
    esac
}

expand_path_uri
if [ "$LINKHANDLER_EXPAND_ONLY" = 1 ]; then
    printf "%s\n" "$link"
    exit 0
fi
[ -e "${link}" ] && try_mime_handling || try_custom_uri

killall ssh-agent 2>/dev/null
