#!/bin/bash

read -r -p "name: " name
read -r -p "description: " description
read -r -p "public [Y/n]: " public

case "$public" in
    [Nn]) public=0 ;;
    *) public=1 ;;
esac

[ -d "${CLOUD}/GIT/${name}" ] && printf "Repo already exists\n" && exit 1

[ -e "${CLOUD}/GIT/${name}" ] && printf "File already exists with %s (non-directory)\n" "$name" && exit 1

mkdir "${CLOUD}/GIT/${name}"

git init --bare "${CLOUD}/GIT/${name}"
printf "%s" "$description" > "${CLOUD}/GIT/${name}/description"
[ "$public" = 1 ] && touch "${CLOUD}/GIT/${name}/git-daemon-export-ok"


git remote add cloud cloud@cloud:"${CLOUD}"/DRIVE/GIT/"${name}"
