#!/bin/sh

preproc="$1"

wm="other"
roficmd="rofi -modi drun,run -show drun -theme nord -no-X -icon-theme Infinity"
[ ${WM:-?} = "bspwm" ] && roficmd="$roficmd -monitor $(bspc query -M -m '.focused' --names)"

$preproc $roficmd

# nwggrid
