#!/bin/sh

file="${1:-$HOME/Documents/emoji}"

roficmd="rofi -sort -sort-method fzf -matching fuzzy -theme emojimenu -dmenu"
case "$WM" in
    bspwm)
	bspc query -M && WM="bspwm" || wm="other"
	roficmd="$roficmd -monitor $(bspc query -M -m '.focused' --names)"
	;;
esac
cat "$file" | $roficmd | awk '{print $1}' | tr -d '\n' | wl-copy
