#!/bin/sh
sudo setcap cap_sys_admin+ep $(which ffmpeg)

args=""
for arg in "$@"; do
    case "$arg" in
        -mic) args="$args -f pulse -i -" ;;
        -pcaudio) args="$args -f pulse -i alsa_output.pci-0000_2f_00.4.analog-stereo.monitor" ;;
    esac
done

ffmpeg $args \
    -device /dev/dri/card1 -crtc_id "$(modetest -p | sed -n '/^[[:digit:]]/p' | head -n1 | awk '{print $1}')" \
    -f kmsgrab -i - \
    -vf 'hwmap=derive_device=vaapi,hwdownload,format=bgr0' \
    "$(date)".mp4
