#!/bin/sh

ssh cloud cd services/aio-limas ';' git pull origin master
[ -z "$1" ] && \
    ssh cloud cd services/aio-limas ';' GO=/home/cloud/go/bin/go ./buildonly && \
    ssh -p 8023 user@10.0.0.2 cd services/aio-web ';' ./update

