#!/bin/sh

# killall hyprpaper
# hyprpaper & disown

awww kill
[ -e "/run/user/1000/awww.socket" ] && rm "/run/user/1000/awww.socket"
awww-daemon & disown

[ -f "$SYSTEM_IMAGES/desktop.png" ] && awww img "$SYSTEM_IMAGES/desktop.png"
for wallpaper in "$SYSTEM_IMAGES/desktop"*.png; do 
    output="${wallpaper##*desktop}"
    output="${output%.png}"
    awww img "$wallpaper" -o "$output"
done
