#!/bin/bash
# killall waybar
# for mon in "${XDG_CONFIG_HOME}/waybar/"*.json; do
#     waybar -c "$mon" -s "${mon%.json}.css" & disown
# done
#
#

killall eww

eww open hyprland-bar-dp
eww open hyprland-bar-hdmi
