#!/bin/bash

window_match="$1"
isniri=0
if niri msg windows >/dev/null 2>&1; then
    isniri=1
    cmd="niri msg -j windows"
    jqPath='.[]|"\(.title)\t\(.id)"'
else
    cmd="hyprctl clients -j"
    jqPath='.[]|"\(.title)\t\(.address)"'
fi

window_columns=$($cmd |
    jq -r "$jqPath"|
    column -t -s $'\t' -o $'\t')


if [ "$window_match" ]; then
    focused_window="$(niri msg -j focused-window | jq -r '.title')"
    window=$(printf "%s" "$window_columns" |
        grep -Fv "$focused_window" |
        grep -i "$window_match" |
        head -n1)
else
    window=$(printf "%s" "$window_columns" |
        rofi -i -dmenu -theme cat-macchiato)
fi
window="$(printf "%s" "$window" | cut -d $'\t' -f2)"

[ -z "$window" ] && exit

if [ $isniri = 1 ]; then
    niri msg action focus-window --id "$window"
else
    hyprctl dispatch focuswindow address:"${window}"
fi
