#!/bin/sh

wpctl  status |
    awk "BEGIN { sinks = \"no\" }

        !/[[:digit:]]/ { sinks = \"no\" }

        /Sinks:/ { sinks = \"yes\" }

        {
            if (sinks != \"no\") {
                sources[len++] = \$0
            }
        }

        END {
                for(i = 0; i < len; i++)
                    print sources[i]
            }" |
    sed -e 1d -e '$d' |
    rofi -theme nord -dmenu |
    tr -c '[:digit:]' ":" | sed -n 's/:*\([[:digit:]]*\).*/\1/p' |
    head -n1 |
    xargs wpctl set-default
