#!/usr/bin/env bash

state_file="/tmp/tv-mode"

set.wayland() {
    if [ -f "$state_file" ]; then
        # i don't know why i need to use swaymsg here, but apparently I do
        pactl set-default-sink 'alsa_output.pci-0000_2f_00.4.analog-stereo'
        wlr-randr --output DP-1 --on
        wlr-randr --output HDMI-A-1 --on
        wlr-randr --output DP-2 --off
        wlr-randr --output DP-1 --pos 0,0
        wlr-randr --output HDMI-A-1 --pos 1920,0
        rm "$state_file"
        killall kodi
        restart-waybar
    else
        wlr-randr --output DP-2 --on
        wlr-randr --output HDMI-A-1 --off
        wlr-randr --output DP-1 --off
        sleep 1
        pactl set-default-sink 'alsa_output.pci-0000_2d_00.1.hdmi-stereo-extra4'
        touch "$state_file"
        kodi & disown
    fi
}

set.hyprland() {
    if [ -f "$state_file" ]; then
        notify-send -c tv-mode "TV MODE" "OFF"
        pactl set-default-sink 'alsa_output.pci-0000_2f_00.4.analog-stereo'
        hyprctl dispatch dpms off DP-2
        hyprctl dispatch dpms on DP-1
        hyprctl dispatch dpms on HDMI-A-1
        for i in {1..4}; do
            hyprctl keyword workspace "${i},monitor:DP-1"
        done
        for i in {5..9}; do
            hyprctl keyword workspace "${i},monitor:HDMI-A-1,layoutopt:orientation:bottom"
        done
        hyprctl keyword monitor HDMI-A-1,1920x1080@75,1920x0,1
        hyprctl keyword monitor DP-1,1920x1080@165,0x790,1
        hyprctl keyword monitor DP-2,disable
        rm "$state_file"
        killall kodi
        # restart-wallpaper
    else
        notify-send -c tv-mode "TV MODE" "ON"
        pactl set-default-sink 'alsa_output.pci-0000_2d_00.1.hdmi-stereo-extra4'
        hyprctl dispatch dpms on DP-2
        hyprctl dispatch dpms off DP-1
        hyprctl dispatch dpms off HDMI-A-1

        for i in {1..9}; do
            hyprctl keyword workspace "${i},monitor:DP-2"
        done

        hyprctl keyword monitor DP-2,preferred,0x0,1.5

        hyprctl keyword monitor DP-1,disable
        hyprctl keyword monitor HDMI-A-1,disable
        touch "$state_file"
        kodi & disown
        # restart-wallpaper
    fi
}

case "$XDG_SESSION_TYPE" in
wayland)
    case "$XDG_CURRENT_DESKTOP" in
    sway)
        killall waybar
        set.wayland
        waybar &
        disown
        ;;
    Hyprland | X-generic)
        set.hyprland ;;
    *)
        set.wayland
        ;;
    esac
    ;;
esac
