require "user.cmp"
require "user.telescope"
require "user.treesitter"
require 'user.whichkey'
require "user.Lspconfig"
-- require "user.color-picker"
require "user.t-source"
-- require "user.orgmode"
-- require "user.duplicate"
--require "user.sniprun"
require "user.dap"
